# -*- coding: utf-8 -*-
"""Molecular Representation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EEMP_69VRu2V9VjtGSBBQAmTcTPr7f0G
"""

!pip -q install rdkit

import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit import DataStructs
import numpy as np


df = pd.read_csv("ecoli_dataset_cleaned.csv")
print(df.head())
print(df.shape)
print(df["label"].value_counts())

# Check validity
df["valid_smiles"] = df["SMILES"].apply(lambda s: isinstance(s, str) and s.strip() != "" and Chem.MolFromSmiles(s) is not None)

n_total = len(df)
n_invalid = (~df["valid_smiles"]).sum()

print(f"Total rows: {n_total}")
print(f"Invalid SMILES found: {n_invalid}")

# Show invalid rows (if any)
if n_invalid > 0:
    print("\nInvalid row(s):")
    print(df.loc[~df["valid_smiles"], ["SMILES", "label"]].head())

# Filter + Confirm
df = df.loc[df["valid_smiles"]].drop(columns=["valid_smiles"]).reset_index(drop=True)

print(f"\nAfter filtering rows: {len(df)}")
print("Dataset filtered. All SMILES are valid.")

#Convert SMILES to ECFP (Morgan)
from rdkit.Chem import rdFingerprintGenerator

morgan_gen = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2048)

def smiles_to_ecfp_array(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None
    fp = morgan_gen.GetFingerprint(mol)
    arr = np.zeros((2048,), dtype=np.int8)
    DataStructs.ConvertToNumpyArray(fp, arr)
    return arr


# Build X and y
X_list = []
y_list = []

for smi, label in zip(df["SMILES"], df["label"]):
    arr = smiles_to_ecfp_array(smi)
    if arr is not None:
        X_list.append(arr)
        y_list.append(label)


X = np.vstack(X_list)           # shape: (n_samples, 2048)
y = np.array(y_list, dtype=int) # shape: (n_samples,)

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Positives %:", y.mean() * 100)

#Save output files
np.save("X_ecfp2048.npy", X)
np.save("y.npy", y)

# keep a mapping back to SMILES
df.loc[:len(y)-1, ["SMILES", "label"]].to_csv("smiles_labels_valid.csv", index=False)

#Data check
#all-zero fingerprints
all_zero = (X.sum(axis=1) == 0).sum()
print("All-zero rows:", all_zero)

#Duplicate SMILES after filtering
print("Duplicate SMILES:", df["SMILES"].duplicated().sum())

